### ISSUE TITLE
Enquire about the lose of the jupyter notebooks 'generate_triplet_data_{PROPERTY_NAME}.ipynb' in the data directory

### ISSUE THREAD

**Issue by zhf3564859793** [mathcom/COMA#1]
After decompressing the compressed files, the jupyter notebooks 'generate_triplet_data_{PROPERTY_NAME}.ipynb' still can not be found in the data directory. I would appreciate it if you could tell me how to solve it.

**Comment by mathcom** [comment]
I apologize for the inconvenience you've experienced, and I kindly inform you that the jupyter notebook files were intentionally removed.

The reason behind this removal is that the compressed files already contain the outputs of the jupyter notebooks. Since users typically don't require the jupyter notebook files themselves and only need the output data 'rdkit_train_triplet.txt', we made the decision to remove the notebooks.

However, we overlooked updating the README file to reflect this change. I apologize for the confusion this may have caused. To clarify, the jupyter notebook files were intentionally removed, and the compressed files include all the necessary output data.

Now the README file has been updated correctly. I hope you have a smooth experience working with the provided files. If you have any further questions or need any assistance, please feel free to let me know.

**Comment by zhf3564859793** [comment]
Thanks for your nice reply. I really appreciate your help.
